### ISSUE TITLE
Pre-release bugs

### ISSUE THREAD

**Issue by tanelj** [Voog/design-nuuk#1]
**Menüü:** 
* [x] Edit mode: Default menüü korral on menüü sulgemise ja pliiatsi ikoon üksteise peal (FF)
![nuuk-menu-close-edit-Screenshot 2021-01-08 at 14 39 16](https://user-images.githubusercontent.com/378755/104016905-d63f2d00-51bf-11eb-9da3-ea7b93a0e380.png)
* [x] Side menu: Navigatsioonil saab valida taustavärvi, kuid kui valida taustaks tume värv (nt must), siis ei ole menüü tekstid nähtavad.
* [x] Side menu: Side menu korral on disainis ette nähtud footer ala side menu lõpus.
* [x] Side menu: "Product listi" layout korral kuvatakse menüüs ka "Product" tüüpi layoutidega alalehed.
* [x] Menu: Musta tausta puhul ei ole näha (on sama värvi) aktiivset menüüelementi ning hoverdatud mitteaktiivset menüüelementi ja keelemenüü teksti.
* [x] Top fixed menu: Pika lehe korral alla kerides muudab menüü stiili (nagu Top loating), kuigi jääb paigale.
* [x] Pikema pealkirja korral murdub pealkiri mitmele reale. Murdunud elemendi sees peaks reavahe olema väiksem kui elementide vahel.
![nuuk-menu-side longScreenshot 2021-01-15 at 10 43 21](https://user-images.githubusercontent.com/378755/104702542-cfb03880-571e-11eb-924e-adc00b2b27c9.png)
* [x] Lubada peita "Product" tüüpi menüüs (vaikimisi on kuvatud).
* [x] Keelemenüü ja otsingu/ostukorvi ikoonid on nihkes.
![nuuk-menu - Screenshot 2021-02-02 at 09 11 37](https://user-images.githubusercontent.com/378755/106569543-577aad00-653d-11eb-8859-47b950c0ca90.png)
* [x] Top menüü puhul on aktiivne menüü element nihkes
![nuuk-top-menuScreenshot 2021-02-05 at 15 12 55](https://user-images.githubusercontent.com/378755/107038271-f06f2980-67c4-11eb-8ca4-a9400fc05fd7.png)
* [x] Sidebar menüü 2nda taseme aktiivne leht ei ole eritatav
* [x] "Lisa alaleht" ilmub esimese taseme alalehe alla ainult siis kui seal on vähemalt üks alaleht (peaks aktiivse alalehe all alati näha olema)
* [x] Kui top menüü korral on saidi nime ala tühi, siis muidu keskel asetsev menüü nihkub eelvaates vasakule.

**Päis**
* [x] Saidi nime ala (default kujul) on erinev muutmise vaates (hall suurtähed) vs eelvaates (sinine väiketähed).
![nuuk-title-public-edit Screenshot 2021-01-08 at 14 56 18](https://user-images.githubusercontent.com/378755/104018059-e22bee80-51c1-11eb-840e-0cdf00eeefe5.png)
![nuuk-title-public Screenshot 2021-01-08 at 14 55 32](https://user-images.githubusercontent.com/378755/104018048-dfc99480-51c1-11eb-97f9-4f1229ebae43.png)
* [x] Musta tausta korral ei ole search ja ostukorvi ikoone näha:
![nuuk-header-blackScreenshot 2021-01-15 at 15 34 10](https://user-images.githubusercontent.com/378755/104733346-38aba680-5747-11eb-9be4-6f6b2dce75da.png)

**Otsing**
* [x] Otsingu input ala `search-input` peaks olema 100% lai (kuni ristini), et ka suurel ekraanidel oleks mugav klikata.

**Keelemenüü**
* [x] Keelemenüüs on puudu võimalus minna tagasi vaikeolekusse - keel ja lipud.
* [x] Vaikimisi valiku korral katab menüü avanedes lipp keele teksti.
![nuuk-flags-and-name-Screenshot 2021-01-08 at 14 39 39](https://user-images.githubusercontent.com/378755/104017091-274f2100-51c0-11eb-84be-b26a3cabe1f8.png)
* [x] Kui valida "Ainult lipud" läheb lippude seadete dialoog osaliselt browseri nurga taha
![nuuk-only-flags-Screenshot 2021-01-08 at 14 40 08](https://user-images.githubusercontent.com/378755/104017028-0b4b7f80-51c0-11eb-8281-139a3e190d32.png)

**Front page**
* * [x] Front page default väärtus on "#F2F2F2", kui avada värvi pikker ja valida täpsemalt, siis kuvatakse väärtus see väärtus, kuid pikker ei oska näidata värvi asukohta. Sliderite liigutamine nullib väärtuse (nt läbipaistvus). Samas kui kasutaja sisestab käsitsi HEX väärtuse, siis värvi pikker konverdib ta ise ümber RGBA'sse `rgb(242,242,242)`. Ka algväärtus võiks olla siin RGBA'na.
* [x] Kui menüü tasutavärv määrata värvitabelist  "puudub" (kriipsuga värvikast) siis näiliselt ei muutu kohe miski, kuid peale reloadi on kujunduse default värv tagasi. Sama on esilehe "shop" pildi värviga.
* [x] Front page (default - üks header pilt) sisuala juures olev pliiats muudab terve lehe värvi (`body_bg`), samas `front_header_bg_1` (poe pildiga) värv muudab kasutaja jaoks sisu värvi ehk mitte sama piirkonn värvi kus pliiats asub. 
* [x] Front page (mitu header pilti - sama tekst igal slaidil) header alas oleva pildil olevat värvi muutes `front_header_bg_1` jne ei muutu midagi.
* [x] Front page (mitu header pilti - erinev teks igal slaidil) header alas oleva pildil olevat värvi muutes `front_header_bg_1` jne muutub pildi pealmise kihi värv, kuid see ei ole kogu ala laiune (teksti värv sõltub ikka `body_bg` värvist).
* [x] Front page `body_bg` värv mõjutab ka `swiper-content` alas olevat tekstiala värvi, samas ei arvesta seal oileva tasutapildi heleduse/tumedusega
* [x] Ilmselt võiks ka sliderite kasti sisu olla indekseeritav (`data-search-indexing-allowed="true"`)

**Toote listing**
* [x] Kui tootel puudub pilt peaks kuvatama placeholder
* [x] Toote listingu lehe automaatselt genereeruvat toodete sektsiooni (class="content") ei peaks indekseerima  (`data-search-indexing-allowed="false"`), indekseeritud peaks olema ainult selle sees olev "content-body" ala.
* [x] Look closer on lingi praegu stiiliga
* [x] Labeli stiilid puudu
* [x] `product_item` divis on "data-title" ja "data-price" attribuutide vahel tühik puudu:
```
<div class="product_list content-formatted flex_row flex_row-3 mar_0-8-neg pad_40-0"><div class="product_item js-product-item flex_row-3--item scale-up js-product-whith-data"
data-title="Esimene toode"data-price="10.0">
```
* [x] Toote nimel on topelt "class" attribuut '<div class="p14 mar_t-16 bold product_item-title" class="bold">'
* [x] Sisse kirjutatud valuuta asemel tuleb kasutada `product.currency` väärtus `{{ product.price_with_tax | money_with_currency: "EUR" }}` 
* [x] Variatsiooniga toote puhul (`product,uses_variants?`) tuleks kuvada variatsioonide hinnavahemikku, kuid vaid siis kui min ja max väärtused on erinevad `product.price_max_with_tax != product.price_min_with_tax`
* [x] Käsitlemata on `product.out_of_stock?` olukord - siis peaks kuvama vastavat teadet ning ei tohiks saada ostukorvi lisada (vaata disaini), lisaks ei tohi saada sellist toodet ostukorvi lisada.
* [x] Hinnavahemiku korral on kriipsu järel liiga palju ruumi - kriipsude vahe peaks võrdne olema.
![nuuk-price rangeScreenshot 2021-01-21 at 11 02 32](https://user-images.githubusercontent.com/378755/105328086-56aa5880-5bd8-11eb-8890-19953d2c50ec.png)
* [x] Hinnavahemikus on läinud vahetusse min ja max väärtused. Vahemik peaks olema max € - min €
* [x] Tootefilter näeb välja teitsugune kui disainis
* [x] Tootefilter saab nüüd kasutada hinna sorteerimiseks toote (variatsiooni) miinimum hinda `product.price_min_with_tax` (variatsioonideta toote puhul on see võrdne toote hinnaga)
* [x] Pole võimalik tagasi minna toodeta vaikimisi (poodniku sorditud) sortimise juurde. Lisaks valikusse "Default", mis taastaks algse olukorra.
* [x] Kui klikata "add to cart" lingil muutmise vaates siis saab JS vea `Voog.ShoppingCart` puudumise kohta. NB! ostukorvi skript laetakse ja objekt `Voog.ShoppingCart` on saadaval vaid eelvaates ja avalikus vaates.
```
Voog.ShoppingCart.addProductById($(this).data('product-id'))
```
* [x] Kui tootel on nimeks pikk sõna, mis on laiem kui tootenimekirja laisu, siis läheb tekst üle ääre - peaks murduma.
![nuuk-product-lits long Screenshot 2021-01-15 at 14 52 29](https://user-images.githubusercontent.com/378755/104729697-7c031680-5741-11eb-809e-9deafdd56475.png)
* [x] Tootenimekirja kuvamisel on praegu rakendatud animatsioon - praegune animatsioon teeb aeglase tunde. Eemaldame ilmumise animatsiooni (https://share.getcloudapp.com/E0u41p2n).
* [x] Kui tootele on määratud pilt ja järgmistel toodetel ei ole, siis kuvatakse seda pilti ka järgmistel  (muutuja tuleb nullida).
* [x] Toote pilti kuvatakse listingus alati zoomitult (olenemata zoom/fit seadest pilti vaates)

**Tooteleht**
* [x] Kui tootel puudub pilt peaks kuvatama placeholder ka preview vaates
* [x] Toote labeli stiilid on puudu
* [x] Variatsiooniga toote valiku selektil ei ole määratud font-size'i seega on see browseri default (11px). Kui selekti font-size on all 16px siis iPhone zoomib seda välja valimisel automaatselt (https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone). Sama probleem on ka tootenimekirja sorteerimise selectiga.

**Blogi**
* [x] Artiklite listingu osa (`blog_listing-wrapper`) ei tohiks olla indekseeritud (data-search-indexing-allowed="false")

**Artikkel**
* [x] Artikli pildi alt teksti seadete kast ilmub vale koha peale ning placeholder on loetamatu.
![nuuk-article-altScreenshot 2021-01-08 at 15 05 40](https://user-images.githubusercontent.com/378755/104018852-31265380-51c3-11eb-90ec-1d9bc688145f.png)
* [x] Vigase vormipostituse korral tuleks scrollida vormi algusesse - hetkel comment lahtrini. Veel parem kui vorm teeks AJAX postituse.
* [x] Kommentaari emaili väljal peaks olema `type="email"`
* [x] Kommentaari väljade inputid võiksid olla juba `required` flagiga.
* [x] Artikli kommentaaride stiil ei vasta disainile - ikoon puudub. Disainis:
![nuuk-article-comments Screenshot 2021-01-15 at 12 04 26](https://user-images.githubusercontent.com/378755/104711394-fc1d8200-5729-11eb-9a56-01fcdd6fbfdd.png)
* [x] Artikli autori ja kuupäeva värv on css, sisse kirjutatd ning disaini stiilides muudetavad värvid neid ei mõjuta, samas nende separaator kasutab peamist värvi.
![nuuk-stylearticle-authorScreenshot 2021-01-15 at 13 55 43](https://user-images.githubusercontent.com/378755/104724716-bbc60000-5739-11eb-93af-73d81d194e61.png)
* [x] Kommentaaride taustavärvi kontroll läheb disainitööriista

**Footer**
* [x] Footeri sees olev lehepõhine sisuala (footer > content-body) peaks olema indekseeritud (`data-search-indexing-allowed="true"`)
* [x] Ükski `xcontent` sisuala ei tohiks olla indekseeritud, kuna selline otsing annaks välja kõik lehed, mis tekitab müra.
* [x] Footer ala z indeksid on paigast ära sisuala tööriistad ilmuvad tema alla:
![nuuk-footer-Screenshot 2021-02-05 at 14 33 09](https://user-images.githubusercontent.com/378755/107034421-5d7fc080-67bf-11eb-8771-d649220c14bd.png)

**Seaded**
* [x] Kui failipaneel on avatud, siis ilmub paneelilt avanev seadete aken valele kohale
![nuuk-settings Screenshot 2021-01-15 at 09 54 45](https://user-images.githubusercontent.com/378755/104697103-edc66a80-5717-11eb-96c3-66398edd0d52.png)

**Seaded -> Front page header**
![nuuk-setings-front-page-header 2021-01-08 at 15 00 04](https://user-images.githubusercontent.com/378755/104018345-48b10c80-51c2-11eb-916a-4c4cfe296338.png)

* [x] Slideri sisuala ei ole muudetav (taust on ees) juhul kui on vaid üks head image.
* [x] "Number of head images" võiks olla esimene valik
* [x] "Use fade effect" ja "differnet titles" võiks ilmuda/olla näha/olla aktiivsed vaid siis kui head images arv on suurem kui 1.
* [x] "Use fide effect" - hetkel fade'ib pilt, kuid tekstid liiguvad vasakule - ka tekstid peaksid fade'ima https://share.getcloudapp.com/eDuw4bYG
* [x] Slaideri nooled on näha vaid muutmise vaates, mitme slaidi korral peaksid olema alti nähtaval (k.a. fade korral)
* [x] Mitme slaidi korral peaks saama valida, kas "Autoplay" yes/no.
* [x] "Autoplay" korral peaks saama muuta intervalli pikkust.

**Sisuala stiilid**

* [x] Sisualas olev "button" stiiliga objekti tekst ei ole vaikimisi seadete korral näha (on sama värvi).
* [x] Pealkirjade reavahed on komakohtadega
* [x] Pre ploki taust on valge - disainis hall
* [x] "blockquote" lõik ei ole disaini stiiliga. Disainis:
![nuuk-style-blockquote](https://user-images.githubusercontent.com/378755/104696072-5ad90080-5716-11eb-9d9c-3f9dbb2a845a.png)
* [x] Tabeli stiilid ei ole samad, mis disainis
* [x] Pikad sõnad liiguvad üle sisuala äärte. Nii modulaarsetes veergudes, kui üksiku ala puhul mobiilses vaates üksikul alla.
![nuuk-modular-content longScreenshot 2021-01-15 at 10 46 51](https://user-images.githubusercontent.com/378755/104703139-a17f2880-571f-11eb-91a9-8bc8a3b7e115.png)

**Vormid**
* [x] Lahtri tüübil "märkeruut" puuduvad märkeruudud.
![nuuk-form Screenshot 2021-01-15 at 15 31 15](https://user-images.githubusercontent.com/378755/104733058-cd61d480-5746-11eb-842e-9641c8d6c7c6.png)
* [x] Lahtri tüübil "valik" (bullets) puuduvad bulletid
* [x] Select tüüpi välja font on browseri default (11px)
* [x] Musta tausta korral ei ole submit nuppu näha.
* [x] ReCapcha badge asukoht peaks olema all paremas nurgas, kuid mingi element mõjutab ta asukoha kõrgemale.
![nuuk-recapchaScreenshot 2021-02-05 at 14 11 05](https://user-images.githubusercontent.com/378755/107032259-3378cf00-67bc-11eb-8eed-9b1f14f4e66a.png) (Eraldi issue)

**Password protected pages**

* [x] Välja logimise nupp võiks olla värskema stiiliga (Next)
![nuuk-logout Screenshot 2021-01-21 at 16 48 57](https://user-images.githubusercontent.com/378755/105367100-c0425b00-5c08-11eb-8baf-385d0e00e50a.png) (eraldi issue)

**Disainieditor**
* [x] `header-mainmenu-font-size` ei rakendu menüüle (on kasutusel `.menu-sub .menu-item a` kuid leidub täpsem selector: `.menu-main .menu-sub.active .menu-item a`
* [x] `--product-list-item__alignment: left;` vaikeväärtus `left` ei ole seadetes defineeritud peaks ilmselt olema `flex-start`.
* [x] Vormi teksti stiilid (underline, bold jne) mõjuvad märkeruut/valik valikutele - kas peaksid tegelikult mõjuma label'itele?

**JS vead**

* [x] Akna suuruse muutmine saab JS vea

```
Uncaught ReferenceError: handleMenuPos is not defined
    handleWindowResize application.js?v=1:1120

  // Initiates the table horisontal scroll function when window is resized.
  var handleWindowResize = function() {
    $(window).resize(debounce(function() {
      handleActivLangMenu();
      handleMenuPos();
```
* [x] Pickeri kaudu värvi muutmine (kui on ka taustapilt ja see on puudu) tehakse asjata `/none` päringuid. Põhjus:
```
$imageEl.attr('src', 'none');
$imageEl.attr('srcset', 'none');
```

siin HTML attribuudi `'none`` väärtuse asemel mõeldud ilmselt tühiväärtust `''`.

**HTML vead**
* [x] `body_bg_color` väärtus võib olla ka tühi sel juhul ei tohiks ka tema stiili renderdada (või alternatiiv veendua, et väärtus oleks `"none"`)
```
body > .body-bg_color {
  background-color: {{ body_bg_color }};
}
```

* [x] "Product" layoutis on `<div class="container_wrap">` divi lõputag puudu

**Üldine**
* [x] Kasutame disaini prefix nimega js,css versioone `main.min.css?v=2.2` asemel `main.min.css?v=nuuk-2.2`
* [x] `popup_share('http://twitter.com` peaks olema "https"  `popup_share('https://twitter.com"``
* [x] Veenduda, et Liquidiga renderdatav HTML attribuudi sisu on escape'itud (nt `alt="{{_altAttr}}"` asemel `alt="{{_altAttr | escape_once}}"`) saab otsida `="{{`.

**Tekstid ja tõlked**
* [x] Sisse kirjutatud tekstid: `LOOK CLOSER`, `ADD TO CART`

**Optimeerimine**
* [x] Optimeerida kasutatud pildi (nt https://tinyjpg.com/)

**Default sisu**
* [x] Default sisus olevad näidispildid teha kättesaadavaks `https://static.voog.com/voogstock/` skoobis (hiljem).
* [x] `modular-content-1-1` default sisus võiks olla peale pilti `<br/>` tag, et lihtsustada vaikealal klikamist.

**Comment by annes-aus** [comment]
**Keelemenüü**

- [ ] Lehel allapoole kerides avaneb keelemenüü vales kohas või ei avane üldse:
<img width="952" alt="Screenshot 2021-01-08 at 15 29 19" src="https://user-images.githubusercontent.com/48431621/104021799-10acc800-51c8-11eb-97a0-d1cea72c6dca.png">

**Comment by Jkapsta** [comment]
- [ ] Esilehe headeri sisuala ei saa tagasi kui ära kustutad, ainuke viis on lisada teine pilt, siis taastub
![image](https://user-images.githubusercontent.com/72735579/104026954-5d47d180-51cf-11eb-9d9b-9a14809c32e0.png)

- [ ] Esilehe headeri sisuala teksti kustutamine jätab liiga väikse ala kuhu ei saa klikkata
![image](https://user-images.githubusercontent.com/72735579/104028037-e3b0e300-51d0-11eb-9411-987aac9335fc.png)

- [ ] Product list mallis ei saa muuta pildi zoom taset, ainult ruut/sisse zoomitud
![image](https://user-images.githubusercontent.com/72735579/104027092-95e7ab00-51cf-11eb-8476-98a293839e4b.png)

- [ ] Uue (paintbucket) ikooni menüü ei jõua scrollimisele järele

- [ ] Scrollides muutub ülemise menüü taust natuke liiga kiiresti, ei näe sujuv välja. (pole otseselt bug)

**Comment by hennrunnel** [comment]
### Eriseaded

- [ ] “Top - fixed in header” valiku puhul ei peaks skrollimisel menüü taust valgeks lülituma
![image](https://user-images.githubusercontent.com/11610902/104163611-5e5f4580-53ff-11eb-94ee-c16e47e6c048.png)

- [ ] Kasuta en dashi asemel em dashi ehk “Top - fixed in header” asemel “Top – fixed in header” 

### Nuuki disain

- [ ] Kommentaaribloki taustavärv ei paista läbi. Kas taotluslik?
![image](https://user-images.githubusercontent.com/11610902/104163670-759e3300-53ff-11eb-8035-fe20f030a44e.png)

- [ ] Prev-Next artiklie – edev featuur, aga nupu tekst sulab tumeda pildi korral selle sisse. Kas paneme pildile äkki tugeva läbipaistvuse peale, et tagada teksti loetavus? 
![image](https://user-images.githubusercontent.com/11610902/104163708-864ea900-53ff-11eb-9ea5-4c67d9d59528.png)

- [ ] Seaded > Disainitööriist: puudu on kasutusel oleva šrifti tugi; juhtvärvide muutmisel näitab muutusi ainult “Primary color” muutmine
![image](https://user-images.githubusercontent.com/11610902/104163729-8c448a00-53ff-11eb-9e50-d88f99f83ab6.png)

### UX/UI

- [ ] Kasuta Nuuki eriseadete menüüs samu šrifte ja hover värve, mis CMSi sisemistes menüüdes.
- [ ] Nuuki eriseadete popover menüü nool peaks asetsema ikooni tsentris selle kohal
![image](https://user-images.githubusercontent.com/11610902/104163844-b9913800-53ff-11eb-9b87-56d4ccb85e7c.png)

- [ ] Kas “Common page” malliga alalehel võiks olla visuaalne viis lisada alalehte (“Add subpage”)? Praegu saan seda teha ainult struktuurivaatest, mis on nurga taga.
![image](https://user-images.githubusercontent.com/11610902/104163881-c877ea80-53ff-11eb-846f-751d10ac2d24.png)

- [ ] Kui pood ole veel töökorras ja ma ei saa osta, aga tootepildile skrollides näen võimalust “Add to cart”. Selle klikkimine ei tee midagi. 
![image](https://user-images.githubusercontent.com/11610902/104163922-d7f73380-53ff-11eb-8f4c-66f7b5848ea9.png)

### Kommentaarid UX kohta (mitte taskid)
* “Compare price” oleks mulle kui poepidajale palju selgem hallata, kui see oleks “Product settings” all praeguse malli eriseadete asemel. 
![image](https://user-images.githubusercontent.com/11610902/104164047-01b05a80-5400-11eb-817b-ae45b3cfbcae.png)

***


- Üldine UX segadus – värske poepidajana ei saa hästi aru, et poe jaoks pean “Products” asemel tegema uue “Product list” malliga alalehe.
- Sain värske poepidajana tehtud lehe “Shop”, millel on product list mall. Hästi raske on aru esimesel korral aru saada, kuidas lisada uut toodet. Kas “+Add subpage” asemel võiks ja saaks nupu tekst olla “+Add product page”, mille vaikimisi layouti valik on “Product”?
![image](https://user-images.githubusercontent.com/11610902/104164068-0b39c280-5400-11eb-9132-6dbac9af1f4e.png)

***

* Värske poepidajana on tootelehel hästi keeruline aru saada, et pean lisaks tootelehele looma ka eraldi tooteobjekti, mis on peidus “Buy buttoni” taga 
![image](https://user-images.githubusercontent.com/11610902/104164093-14c32a80-5400-11eb-86a1-fd8c68379868.png)

**Comment by tanelj** [comment]
Disainiküsimused

**Blogi**
* [ ] Nimekirja vaates ei ole tage nt ei saa maha võtta "blog/tagged/minutag". (näidis teisel mallil: https://amsterdam.voog.com/uudised)

**Artikkel**
* [ ] Pilti ei saa välja lülitada (kui artikli juurde ei ole plaanis pilti panna ja placeholder ka ei sobi) (disain?)
* [ ] Esimese/viimase artikli footeris on vaid üks element Previous/next, millel hoverdades ilmuv pilt tundub disainilt kentsakas (sama küsimus ka siis, kui teeme võimaluse, et artiklil võib pilt puududa).
![nuuk-article-prev Screenshot 2021-01-08 at 15 13 49](https://user-images.githubusercontent.com/378755/104019500-549dce00-51c4-11eb-8e9a-5b57210bc2de.png)

**Comment by hennrunnel** [comment]
> * [ ]  Kui pood ole veel töökorras ja ma ei saa osta, aga tootepildile skrollides näen võimalust “Add to cart”. Selle klikkimine ei tee midagi.
>   ![image](https://user-images.githubusercontent.com/11610902/104163922-d7f73380-53ff-11eb-8f4c-66f7b5848ea9.png)
>

Ettepanek: kui pood pole seadistatud või on ajutiselt kinni või on toote mittemüüdavaks märgitud, võiks listingu vaates "Add to cart" teksti asemel kuvada sama teksti, mis toote detailvaatel ostunupul: 
![image](https://user-images.githubusercontent.com/11610902/104586233-e34f9680-566d-11eb-8ded-c51e1011be31.png)

**Comment by hennrunnel** [comment]
- [ ] Eriseadete nupp vajab tooltippi 
![image](https://user-images.githubusercontent.com/11610902/104596887-4694f500-567d-11eb-8e3b-19d70a5b18fa.png)

**Comment by robertpihelgas** [comment]
- [ ] Blokis, tekstisisualas oleva aktiivseks võetiud pildi suuruse muutmise "mummud" on "+ lisa" nupu peal - võiks olla vastupidi:

 
![Screenshot 2021-01-25 at 11 44 23](https://user-images.githubusercontent.com/27947082/105688916-d307a900-5f02-11eb-85df-56be5c6b505e.png)
