### ISSUE TITLE
Buy buttons are active when no variants are selected

### ISSUE THREAD

**Issue by PeeterPaal** [Voog/design-nuuk#79]
Buy buttons should be in disabled state when no variants are selected.

Behaviour in live version
![Screenshot 2021-12-21 at 14 02 27](https://user-images.githubusercontent.com/44435196/146927009-635305ec-ff46-4453-a20a-6ee25d5064c8.png)

Expected behaviour
![Screenshot 2021-12-21 at 14 02 19](https://user-images.githubusercontent.com/44435196/146926995-f61e1811-98b7-45cb-973b-91b259b21772.png)

**Comment by tanelj** [comment]
Fixed by #87
